export * from './create-document.input'
export * from './delete-document.input'
export * from './find-one-document.input'
export * from './remove-document.input'
export * from './restore-document.input'
export * from './restore-document.input'
export * from './update-document.input'